apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-export-metadata
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  history: '{}'
