apiVersion: v1
kind: Service
metadata:
  name: ark-completions
  namespace: {{ .Values.namespace }}
  labels:
    app: ark-completions
spec:
  selector:
    app: ark-completions
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
